### ISSUE TITLE
add button appears twice

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#10]
if I create a new person entity and start typing in the admin note at the end (it seems to only happen once I start typing), the `+` sign appears twice:

![Capture d’écran de 2021-10-20 16-03-14](https://user-images.githubusercontent.com/60868/138108600-8162f608-60fe-4f45-9e6f-21dfa61e02af.png)

**Comment by berger-n** [comment]
ok that's better
let me check this

**Comment by berger-n** [comment]
looks fixed to me:

![Screenshot_20211020_164820](https://user-images.githubusercontent.com/33383857/138116546-164643c3-a9d7-4cbd-a98c-38145ef9a4a7.png)
