### ISSUE TITLE
fix mixing data between different kinds of shapes

### ISSUE THREAD

**Issue by berger-n** [buda-base/blmp-client#14]
- [x] fix loading profile after another entity has been loaded 
- [x] fix closing/highlighting in left menu 
- [x] initialize undo/redo
- [x] fix mixing data from profile and entity after both are loaded then switching from one to the other

~~fix undo when navigating multiple times from/to profile from/to open entity~~
~~fix loading profile from left menu when in session at startup~~
~~fix glitches when navigating between profile and other entity using left menu~~

**Comment by berger-n** [comment]
steps to reproduce:
1. checkout branch https://github.com/buda-base/blmp-client/tree/debuglog_14
2. close all entities/profile then reload
3. load P1 from `/new`
4. load profile
5. click on P1
6. clear console
7. click on profile / user on the left

logs say it's adding personNames etc. to user via onSet/onUpdateValues listener:

![Screenshot_20211104_144539](https://user-images.githubusercontent.com/33383857/140324592-849fb701-12a8-42a7-8910-1481395f3321.png)

which can then be found in user undo history:

![Screenshot_20211104_144804](https://user-images.githubusercontent.com/33383857/140325073-4d22f21b-b202-49f3-b8c6-baffd97b1f38.png)

this related to recent changes around here: 
https://github.com/buda-base/blmp-client/blame/debuglog_14/src/helpers/rdf/io.ts#L325

**Comment by berger-n** [comment]
simpler way to reproduce, once user profile and P1 are loaded:
1. reload from user profile
2. click on P1
3. clear console
4. click on profile / user on the left

now I need to figure out why rendering `EntityEditContainer` for `tmp:user` triggers `getAtomForProperty` on P1 `Subject`:
![Screenshot_20211104_185346](https://user-images.githubusercontent.com/33383857/140393186-d26d7b9a-5407-4269-832c-44fde99d9712.png)

**Comment by berger-n** [comment]
issue was about ensuring right shape was used with right entity when using left menu 
(see especially https://github.com/buda-base/blmp-client/blame/master/src/helpers/rdf/io.ts)
closing

**Comment by eroux** [comment]
excellent, thanks a lot!

**Comment by berger-n** [comment]
could reproduce again:

1. load G10
2. load P1
3. reload
4. click on G10 in left menu
5. click on P1 in left menu
6. P1 gets modified state and some place properties are visible in its history log:

![image](https://user-images.githubusercontent.com/33383857/149928130-5b508df4-bbc2-4fe9-9871-5121448d950d.png)

![image](https://user-images.githubusercontent.com/33383857/149928229-462d00de-0dd5-4d4a-ae96-a0b1ebbe1b9c.png)

**Comment by berger-n** [comment]
fixed, cannot reproduce anymore, closing
