### ISSUE TITLE
use field as prefLabel

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#17]
In the cases of person and instance, there are two sets of names:
- the prefLabel
- the names of the person / titles of the instance

in the data they are independent, but it's not very convenient if they are independent in the UI, since 99% of the time the prefLabel will be one of the names / titles.

A proposal is:
- have a button "use as label" in each title / name
- on onBlur of the input field of a name / title: if there is currently no prefLabel in the language of the name / title, add the name / title as prefLabel automatically (caveat: `bo` and `bo-x-ewts` are the same language

This case will be detected with the `bds:allowPushToTopLevelSkosPrefLabel true` (not the most elegant name but...)

**Comment by berger-n** [comment]
done, I've also put type & label/language on one line to keep things compact for Karma: https://editor.bdrc.io/edit/bdr:P3379/bds:PersonShape

![image](https://user-images.githubusercontent.com/33383857/156177319-7808551f-f00e-4814-b809-03803af10e03.png)

you can manually add/replace top level prefLabel for this language using button which appears on hover
or automatically when closing property group/opening another (it will copy label if there isn't any for this language)

**Comment by eroux** [comment]
ah the one line thing works really well, thanks a lot!

I think the button could be improved a bit... I'm thinking of [this icon](https://www.iconfinder.com/icons/2808169/label_tag_discount_price_shopping_icon), perhaps preceded by [this one](https://www.iconfinder.com/icons/9021533/number_circle_one_bold_icon) (or maybe a mix of the two a bit like [this one](https://www.iconfinder.com/icons/619260/circle_gold_honor_medal_number_one_ribbon_1_icon) ?). The text on hover could be "use as the main name or title for this language". Otherwise excellent, thanks!

**Comment by berger-n** [comment]
ok! tried something like that: https://editor.bdrc.io/edit/bdr:P3379/bds:PersonShape

![image](https://user-images.githubusercontent.com/33383857/156185860-4bcc7f74-0990-419c-9bbf-522f52d2ea4f.png)

**Comment by eroux** [comment]
that's a bit better! Let's change the button a bit more:
- rectangular, red background, white outline for the icon
- icon is the label icon followed by an arrow up, something [like that](https://www.iconfinder.com/icons/5388642/arrow_direction_navigation_square_up_icon)
- the text only appears on hover on the button

**Comment by berger-n** [comment]
updated icon/button:

![image](https://user-images.githubusercontent.com/33383857/156201369-4c4ad01b-3cee-4cd4-8034-e027be584b4b.png)

**Comment by eroux** [comment]
perfect, thanks! maybe a bit more padding around the icons

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/156339374-c818e6d9-44f1-4e83-b282-36b9fe2c0832.png)

**Comment by eroux** [comment]
good! let's move things around a bit: 
- vertically align the middle of the `+` and `-` with the middle of `en`
- vertically align the middle of the label icon with the middle of the closing cross
- widen the label icon a bit: a bit more padding on the left and right, and a bit more space between the two icons
- horizontally align the middle of the closing cross with the middle of the `+`
- horizontally align the label icon with the `-` (I'm not sure how)

**Comment by berger-n** [comment]
done: 

![image](https://user-images.githubusercontent.com/33383857/156363813-9a10d3eb-0f7e-484a-a31d-486483f6ee42.png)

**Comment by eroux** [comment]
ah yes, much better, thanks! now we should balance:
- the space on top of the cross with the space on the right of the cross (so making it a bit lower probably, or adding some padding at the top)
- the space left of the plus, the space between the plus and the minus, and the space right of the plus

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/156548942-161f8196-d1c3-4ff6-9b5f-33c6d29e7231.png)

**Comment by eroux** [comment]
perfect, thanks!
