### ISSUE TITLE
css improvement for facet in facet

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#18]
The only case we have of that in the data is contentLocation in the note, which currently looks like:

![Capture d’écran de 2022-03-01 15-23-18](https://user-images.githubusercontent.com/60868/156189162-86d59dde-d00e-4243-9c85-0ef46d68aaee.png)

which should be improved. I think in order to be consistent we should have the same style of button we have for facets at the top level (ex: notes, names, etc.)

**Comment by eroux** [comment]
also it doesn't seem to appear in some cases (here `/edit/bdr:P667/bds:PersonShape`):

![Capture d’écran de 2022-03-01 15-52-44](https://user-images.githubusercontent.com/60868/156191802-c12fad9b-06d7-4a4c-a522-dc9a660a4c15.png)

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/156367164-867eb798-29ac-4e86-8543-1b0d99e506b5.png)

![image](https://user-images.githubusercontent.com/33383857/156367219-c1de5f53-afd7-4045-851e-d1e2384a6dff.png)

**Comment by eroux** [comment]
perfect, thanks a lot!
