### ISSUE TITLE
minor css / tooltip improvements

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#19]
In the following screenshot there are a few issues:

![Capture d’écran de 2022-03-01 15-52-44](https://user-images.githubusercontent.com/60868/156191998-e7267e03-eeca-4610-8263-7fcacb148b62.png)

- "Source" (the red one) should be closer to the field below than it is to the text above
- "search name or RID" should be "search name or RID for source" (so that it's clearer)

Finally, I'm not sure about this but I think it's worth looking at: when there's currently no value on a field (ex: "source statement"), instead of having like we have now "source statement" at the top and then an empty line, we could have either:
- source statement at the top like it is now, and in the field, in gray, the help message (but in that case it's way too long... so let's not do that now)
- nothing at the top, and "source statement" in the field in gray, then once the user types in the field, "source statement" moves at the top

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/156379817-35df21c8-b8a5-4f77-9935-8cfeab5a2488.png)
