### ISSUE TITLE
handling dates

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#20]
This is a rather complex issue (more than I anticipated): we want to use a format for the value of `bdo:onOrAbout` that is [EDTF](https://www.loc.gov/standards/datetime/), it has been integrated in [ISO8601-2019](https://www.iso.org/obp/ui/#iso:std:iso:8601:-2:ed-1:v1:en).

Apart from the uncertainty of datatype to use in RDF (we'll keep `xsd:string` at the moment), there are a few issues:
- [x] validating the input, with a proper help message. I think this could be done with [edtf.js](https://github.com/inukshuk/edtf.js). In the case where the date is not in a valid format, there should be a pretty long error message that I can write in the `sh:message` of `bds:EventShape-onOrAbout`
- [x] indicate that the field should be in EDTF format, I can't find a proper solution to that apart from a new property `bds:specialPattern` that will have the value `bds:PatternEDTF` (we can add `bds:PatternISBN` at some point too)
- [x] convert the EDTF date to the `bdo:inYear` or `bdo:notBefore` and `bdo:notAfter` fields automatically (which should be easy with edtf.js), keeping the EDTF value
- [ ] hide the inferred fields
- [ ] when the field is not present but `bdo:inYear`, `bdo:notBefore` or `bdo:notAfter` are present, generate it automatically with this data and hide these fields

**Comment by berger-n** [comment]
first one done (considering is #21 a separate issue):

![image](https://user-images.githubusercontent.com/33383857/156590806-78cd20c7-8d7c-4057-8d33-957d18aab043.png)

![image](https://user-images.githubusercontent.com/33383857/156591085-dfc6fc21-53a7-4fc3-8e61-ad06ae0c01a3.png)

**Comment by eroux** [comment]
excellent, thanks! Although I'm a bit surprised that `1` doesn't work... what if we want to refer to year 1 ?

**Comment by eroux** [comment]
ah ok yes, that's fine

**Comment by berger-n** [comment]
third one done:

![Kazam_screencast_00080 mp4](https://user-images.githubusercontent.com/33383857/156798476-bed10397-8dc8-4b19-9c7f-5cd9587f19a0.gif)
