### ISSUE TITLE
EDTF humanizer

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#21]
as a help for the dates field, it would be good to have a humanizer for EDTF that we can plugin in the same UI space as the Unicode preview for Wylie fields. The humanizer could then be used on PDL to display the date.

There's a [PHP library](https://github.com/ProfessionalWiki/EDTF#humanizing) and a [Ruby gem](https://github.com/duke-libraries/edtf-humanize) to take inspiration from, but no JS library...

We can start with the most important patterns, in that order (it has to be recursive):
- `[x,y,z]`  => `x, y or z`
- `{x,y,z}` => `x, y and z`
- `x/y` => `between x and y`
- `x/` => `not before x`
- `/x` => `not after x`
- `x~` => `circa x`
- `x?` => `x?`
- `x%` => `circa x?`
- `zXX` => `(z+1)th c.` (ex: `12XX` => `13th century`

**Comment by berger-n** [comment]
found this: https://github.com/nicompte/edtfy

**Comment by eroux** [comment]
yes, this is the other way around though (parsing plain English into EDTF)

**Comment by eroux** [comment]
ah I see... I think it will be easier once we integrate edtf.js, we can make use of it for parsing

**Comment by berger-n** [comment]
> there seems be an associated "backwards" package: https://github.com/nicompte/unedtfy

installed it, could only parse edtf date but not export it to human-readable format though
I guess it's normal since there seems to be only one initial commit in the repo (see [`/tests`](https://github.com/nicompte/unedtfy/blob/master/tests/common/level0.js))

**Comment by eroux** [comment]
yes, let's not rely on it, I'll write the code if you want, I'm just swamped in the list serialization issue

**Comment by berger-n** [comment]
no problem! I can do it, should be straightforward

**Comment by berger-n** [comment]
needs some further testing but almost done:

![image](https://user-images.githubusercontent.com/33383857/156606246-dd5a12bd-9b18-4768-9f6a-7f949871143d.png)

beside an annoying soon-to-be-fixed UI bug moving cursor while typing when an error is detected, some oddities though: 
- in and-or pattern, using %, ? and ~ not working at the right but ok at the left of date (like in this screenshot) 
- not possible to use 18XX? or 18XX~ but ok for 18?, 18~, 18% (not in a and-or-between pattern though)

**Comment by eroux** [comment]
great! this is enough for a first iteration!

**Comment by berger-n** [comment]
added EDTF error message when more informative than "syntax error" or "no parsing possible":

![image](https://user-images.githubusercontent.com/33383857/157066252-c1cc36c7-fdbe-4830-aced-ca081a01246d.png)
