### ISSUE TITLE
show error message when empty integer field

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#22]
for instance in the image group shape, volume number is mandatory but it doesn't show in the UI:

![Capture d’écran de 2022-03-03 12-43-05](https://user-images.githubusercontent.com/60868/156558557-bcb11bff-12cb-4af0-9629-03b54700eb48.png)

**Comment by berger-n** [comment]
done: 

![image](https://user-images.githubusercontent.com/33383857/157069701-f1b401a4-d00c-4e73-bbfb-0c3fc192fbcd.png)
