### ISSUE TITLE
adjustments for literal selects

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#23]
in the user profile there are two of them, but they look a bit broken (the same label is displayed twice in a row, and the + and - are not aligned:

![Capture d’écran de 2022-03-03 17-19-28](https://user-images.githubusercontent.com/60868/156606776-8dee9de1-1647-46e7-84d0-2a395808b316.png)

**Comment by berger-n** [comment]
fixed:

![image](https://user-images.githubusercontent.com/33383857/156616218-7b27c3c8-39a7-407f-8e4a-b5a2c92b3dd1.png)

**Comment by eroux** [comment]
perfect, thanks!
