### ISSUE TITLE
add buttons to scan request  page

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#41]
On the scan request page, there should be 
- a positive integer input field "total number of volumes", defaulting to 1, then transmitted to the request `&nbvols=X`
- an optional string + lang input field "scan info", then transmitted to the request `&scaninfo=X&scaninfo_lang=en`

**Comment by eroux** [comment]
and let's also add an input field "reproduction of" that is optional but fills by default with "M"+the value of the "image instance" field (it doesn't need to be synchronized at each key stroke, it can be just left empty by default). It is always sent in the query though, through the parameter `instance=`

**Comment by berger-n** [comment]
done: 

![image](https://user-images.githubusercontent.com/33383857/203532435-2f29912f-3e63-4a5e-af2e-2f4787dd3526.png)

which leads to: https://editserv.bdrc.io/bdr:W12827/scanrequest?IDPrefix=1NB&nbvols=1&scaninfo=test%20%C3%A0%20%C3%A9&scaninfo_lang=en&instance=bdr:MW150

not sure where to update https://editor-dev.bdrc.io/ though? or do I deploy in prod?

**Comment by eroux** [comment]
great, thanks! Let's deploy in prod as soon as I have the server code ready (probably tomorrow)

**Comment by berger-n** [comment]
done: https://editor.bdrc.io/scanrequest

![image](https://user-images.githubusercontent.com/33383857/205674521-8f453945-acf5-41fd-8ca2-908bf8a6b612.png)
