### ISSUE TITLE
improving display of dash:URIEditor

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#44]
in the current editor (ex: https://editor.bdrc.io/edit/bdr:PR1TIBET00/bds:CollectionShape ), it's possible to edit objects of rdfs:seeAlso but not to add or remove one, strangely... perhaps we could also use `<input type="url">`

**Comment by berger-n** [comment]
works better now: https://editor.bdrc.io/edit/bdr:PR1TIBET00/bds:CollectionShape

![image](https://user-images.githubusercontent.com/33383857/217852141-e00bb961-2453-4715-8859-e76e19d1e6bf.png)

**Comment by berger-n** [comment]
but "*Shacl did not validate*" when saving this: 

```
bdr:PR1NB260    a bdo:Collection;    
         rdfs:seeAlso "http://test.com"^^xsd:anyURI;    
         skos:prefLabel "test"@en.
```

**Comment by eroux** [comment]
looks perfect, thanks!
