### ISSUE TITLE
route to create entity with a specific ID

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#45]
I tried to create an entity (an instance) with a specific ID but couldn't find any way to do so in the current editor... I think it's almost possible but it doesn't currently work. Let's add a proper mechanism for that.

For now it can be just a route so that going to a certain URL can trigger it. Later when the user tries to open an entity that doesn't exist, they could be asked "do you want to create a new entity with this ID?" and then directed to that route

**Comment by berger-n** [comment]
adding the dedicated route was indeed straightforward: https://editor.bdrc.io/new/bds:PersonShape/named/bdr:P1NB0000

![simplescreenrecorder-2023-03-13_18 33 00 mkv](https://user-images.githubusercontent.com/33383857/224782117-8d8870f8-72cb-4f87-9ae5-5dd32335eb25.gif)

**Comment by eroux** [comment]
perfect, thanks!
