### ISSUE TITLE
language detection in editor fields

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#49]
For a project involving native Tibetans, it would be much easier for them if the lang tag automatically switches to `bo` when the field is in Tibetan Unicode

**Comment by berger-n** [comment]
done: https://editor.bdrc.io/

![simplescreenrecorder-2023-09-14_17 27 38 mkv](https://github.com/buda-base/blmp-client/assets/33383857/e8d02316-f898-4847-b635-4db1bdac2fd0)

**Comment by eroux** [comment]
excellent, thanks!
