### ISSUE TITLE
withdrawing editor

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#5]
There should be a tool with two simple fields, representing the RID that will be withdrawn, and the RID that it will be redirected to. I think there's already an API for that but it remains to be tested. The idea is to keep things simple, a bit like https://www.wikidata.org/wiki/Special:MergeItems

**Comment by eroux** [comment]
the main feature will be to display some strings from the API. The API will return a JSON array of strings that should be displayed, one per line. For instance:

```json
"changes": [
  ["del", "bdg:MW123", "bdr:MW123", "bdo:instanceOf", "bdr:WA123"],
  ["add", "bdg:MW123", "bdr:MW123", "bdo:instanceOf", "bdr:WA456"],
  ["del", "bdg:WA123", "bda:WA123", "adm:status", "bda:StatusReleased"],
  ["add", "bdg:WA123", "bda:WA123", "adm:status", "bda:StatusWithdrawn"],
  ["add", "bdg:WA123", "bda:WA123", "adm:replaceWith", "bdr:W456"],
],
"labels": {
  "bdg:MW123": {"en": "some label"},
  "bdr:WA456": {"en": "some other label"}
}
```

**Comment by berger-n** [comment]
UI is ready: https://editor.bdrc.io/withdraw

![image](https://user-images.githubusercontent.com/33383857/167638508-c3a8a0a2-9b5d-4a43-a78e-d45662a55fed.png)

![Kazam_screencast_00085 mp4](https://user-images.githubusercontent.com/33383857/167639221-a38e5ba1-6584-43ce-b4ea-0c8a9556ce38.gif)

**Comment by berger-n** [comment]
done: https://editor.bdrc.io/withdraw

![image](https://user-images.githubusercontent.com/33383857/207575700-22e263ba-88cd-45ff-985d-9502a9215ae4.png)

- teacher has been replaced here: https://library.bdrc.io/show/bdr:P1NB659
- replaceWith has been updated here: https://library.bdrc.io/show/bdr:P1NB660 and https://library.bdrc.io/show/bdr:P1NB661
