### ISSUE TITLE
add n rows in the outline editor

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#54]
add button to add N rows

**Comment by berger-n** [comment]
done: https://editor.bdrc.io/outline/bdr:W2NB2

![simplescreenrecorder-2024-02-15_18 24 35 mkv](https://github.com/buda-base/blmp-client/assets/33383857/055c2d2f-1849-4050-a19e-4c4dc6389faa)

**Comment by eroux** [comment]
looks perfect, thanks!
