### ISSUE TITLE
add "view on BUDA" button on outline editor

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#55]
with a `?v=...` in the URL

**Comment by berger-n** [comment]
done: https://editor.bdrc.io/outline/bdr:W2NB4
(the link leads to the image instance record for now, not sure how to find the relevant version? maybe using something returned in the header for the csv, wdyt?)

![simplescreenrecorder-2024-02-20_10 43 32 mkv](https://github.com/buda-base/blmp-client/assets/33383857/c9be1dc8-4768-4202-95bd-36abe33eaabe)
