### ISSUE TITLE
outline editor can't import some csv files

### ISSUE THREAD

**Issue by eroux** [buda-base/blmp-client#57]
For instance this one:

[W00KG04062.csv](https://github.com/buda-base/blmp-client/files/14340663/W00KG04062.csv)

results in the following:

![Capture d’écran de 2024-02-20 08-07-21](https://github.com/buda-base/blmp-client/assets/60868/f99b59ca-dd27-4eb2-8b69-427cda8a9573)

**Comment by eroux** [comment]
Hmmm, CSV doesn't require quotes unless there's a `,` inside a cell, this file should be working, maybe a configuration of the js csv reader?

**Comment by berger-n** [comment]
no indeed... still trying to get what's wrong here!

**Comment by berger-n** [comment]
fixed: https://editor.bdrc.io/outline/bdr:W2NB8

![simplescreenrecorder-2024-02-20_12 01 26 mkv](https://github.com/buda-base/blmp-client/assets/33383857/c8ba754a-cfda-4760-81a7-7ee0d548db62)

**Comment by eroux** [comment]
great, thanks!
